In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [2]:
import numpy as np # not really necessary due to pylab

## Array creation routines

In [3]:
np.array(((1,2,3),(5,6,7)))

array([[1, 2, 3],
       [5, 6, 7]])

In [4]:
x = np.ones((2,3))
print (x)

[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
y = np.random.uniform(low=-1,high=1,size=(2,3))
#y = np.random.uniform(-1,1,(2,3))
print(y)

[[-0.22429274  0.6821123   0.62778918]
 [ 0.29574058 -0.30825012  0.90993136]]


In [10]:
x = np.full((2,3), 2.0)
print(x)

[[2. 2. 2.]
 [2. 2. 2.]]


In [12]:
x.shape, x.size,x.dtype

((2, 3), 6, dtype('float64'))

## Operations

In [13]:
x*y

array([[-0.44858548,  1.3642246 ,  1.25557836],
       [ 0.59148117, -0.61650023,  1.81986272]])

In [17]:
x+y

array([[1.77570726, 2.6821123 , 2.62778918],
       [2.29574058, 1.69174988, 2.90993136]])

In [15]:
np.exp(y)

array([[0.79908118, 1.97805156, 1.87346411],
       [1.34412143, 0.73473153, 2.48415201]])

In [16]:
np.dot(x,y.T)

array([[2.17121748, 1.79484365],
       [2.17121748, 1.79484365]])